### PR TITLE
Make top 100 Schools badge not show bottom 100 schools (secondary)

### PR DESCRIPTION
**Pull request by thadk**
This is a school outside Korogwe in NorthEastern Tanzania, one of the lowest performing districts according to the open data overall. It seems for secondary schools, the criteria for "Top School" and "Top 100 most improved" badge got flipped, same for the "Top 40" list itself. Nice job overall. To even be able to start asking these questions visually is amazing.

Before:
https://www.dropbox.com/s/i6lel5tqoq4wpxc/Screenshot%202015-10-20%2011.24.20.png?dl=0

After:
https://www.dropbox.com/s/5mko64dgstphm1e/Screenshot%202015-10-20%2011.24.07.png?dl=0

### CODE REVIEW

**Comment by thadk** [comment]
The Top 40 & Top 100 lists may still need to be updated somehow:
image

**Comment by thadk** [comment]
Okay, now both Badges and Ranked List are correctly sorted (my commits were backwards though).
image

**Comment by thadk** [comment]
The Most-Improved-School calculation is questionable on this one:
https://www.dropbox.com/s/5mko64dgstphm1e/Screenshot%202015-10-20%2011.24.07.png?dl=0
Should a school that has been in the top 100 for past 20 years be most improved (using DESC)? 
At the same time this other one shouldn't be most improved either (ASC), since it has been at bottom for a while (I'm not as sure about this one):
https://www.dropbox.com/s/i6lel5tqoq4wpxc/Screenshot%202015-10-20%2011.24.20.png?dl=0

**Comment by esoliani** [comment]
Is there a jira for this change request?
The list is order base on AVG_GPA, and the lower the value, the better it is. The value that we are showing is the passrate. It may look like it's not sorted properpely.
Please point the jira so we could discuss it.

**Comment by esoliani** [comment]
closing pull request since there is not jira for it.

**Comment by esoliani** [comment]
https://jira.dgfoundation.org/browse/TSD-128

**Comment by esoliani** [comment]
In order to fullfil the issue, we need to change the brackets service, in order to change the color on the legend

**Pull request closed without merging**
